// generated by Fast Light User Interface Designer (fluid) version 1.0300

#include "basic_ui.h"

Basic_UI::Basic_UI() {
  { win_ = new Fl_Double_Window(285, 262, "Basic test");
    win_->box(FL_PLASTIC_UP_BOX);
    win_->user_data((void*)(this));
    { push_ = new Fl_Button(15, 20, 130, 30, "Push me!");
    } // Fl_Button* push_
    win_->set_modal();
    win_->size_range(280, 157);
    win_->end();
    win_->resizable(win_);
  } // Fl_Double_Window* win_
}

Basic_UI::~Basic_UI() {
  delete win_;
}
