// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef basic_ui_h
#define basic_ui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>

class Basic_UI {
protected:
  Basic_UI();
  Fl_Double_Window *win_;
  Fl_Button *push_;
public:
  virtual ~Basic_UI();
};
#endif
