// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef basic_ui_h
#define basic_ui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Menu_Bar.H>
#include "editor.h"
#include <FL/Fl_Group.H>
#include <FL/Fl_Round_Button.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Box.H>

class Basic_UI {
protected:
  Basic_UI();
  Fl_Double_Window *win_;
  static Fl_Menu_Item menu_[];
public:
  static Fl_Menu_Item *file_open_;
  static Fl_Menu_Item *file_exit_;
protected:
  Editor *edit_;
  Fl_Round_Button *op_red_;
  Fl_Round_Button *op_blue_;
  Fl_Round_Button *op_green_;
  Fl_Button *push_;
public:
  Fl_Box *status_;
  virtual ~Basic_UI();
};
#endif
